// Generated by typings
// Source: znk-infra.d.ts
declare module 'znk-infra' {
/** Declaration file generated by dts-gen */

export class Config {
    constructor(...args: any[]);

    getEnv(...args: any[]): void;

}

export class Demo {
    constructor(...args: any[]);

    delayedHello(...args: any[]): void;

    greet(...args: any[]): void;

    greeter(...args: any[]): void;

}

export class Storage {
    constructor(...args: any[]);

    addItem(...args: any[]): void;

    find(...args: any[]): void;

    getAll(...args: any[]): void;

    getItem(...args: any[]): void;

    init(...args: any[]): void;

    updateItem(...args: any[]): void;

}
}
